#!/bin/bash
set -e

function stop_k8s(){
  local IPADDR="$1"
  local ETCD_CLIENT_PORT="$2"
  local K8S_VERSION="$3"
  local K8S_PORT="$4"
  local REGISTRY="$5"

  # Find an API server
  local APISERVER=""
  if curl --insecure -u admin:admin -sf "https://127.0.0.1:${K8S_PORT}" &>/dev/null; then
    APISERVER="127.0.0.1:${K8S_PORT}"
  else
    # If API server is not running on local, searching it from other nodes.
    local NODE_LIST="$(curl -sf 127.0.0.1:${ETCD_CLIENT_PORT}/v2/keys/registry/minions \
                      | jq -r .node.nodes[].key \
                      | sed -n "s/.*\/\(.*\)$/\1/p")"
    local NODE=""
    for NODE in ${NODE_LIST}; do
      if curl --insecure -u admin:admin -sf "https://${NODE}:${K8S_PORT}" &>/dev/null; then
        APISERVER="${NODE}:${K8S_PORT}"
        break
      fi
    done
  fi

  # Drain node in preparation for maintenance.
  docker run \
    --net=host \
    --rm=true \
    "${REGISTRY}/hyperkube-amd64:v${K8S_VERSION}" \
    /hyperkube kubectl \
    drain "${IPADDR}" --force --ignore-daemonsets --delete-local-data

  if [[ "${EXIT}" == "true" ]]; then
    # Exit k8s cluster
    docker run \
      --net=host \
      --rm=true \
      "${REGISTRY}/hyperkube-amd64:v${K8S_VERSION}" \
      /hyperkube kubectl \
      delete node "${IPADDR}"
  fi

  # Remove k8s system pods conf
  echo '{}' | tee /etc/kubernetes/manifests-multi/master-multi.json &>/dev/null
  echo '{}' | tee /etc/kubernetes/manifests-multi/addon-manager-multinode.json &>/dev/null

  echo -n "Waiting for all k8s pods stopped ..." 1>&2
  until [[ "$(docker ps | grep ${REGISTRY}/hyperkube | wc -l)" -le "2" ]]; do
    echo -n "." 1>&2
    sleep 1
  done
  echo 1>&2

  until ! docker ps | grep -w 'k8sup-kubelet'; do
    docker stop k8sup-kubelet 1>/dev/null || true
    docker rm k8sup-kubelet 1>/dev/null || true
  done
}

function exit_etcd(){
  local IPADDR="$1"
  local ETCD_CLIENT_PORT="$2"
  local LOCAL_ETCD="$3"

  # Exit etcd cluster
  local MEMBER_LIST="$(curl -s http://127.0.0.1:${ETCD_CLIENT_PORT}/v2/members)"
  if [[ "${MEMBER_LIST}" == *"${IPADDR}:${ETCD_CLIENT_PORT}"* ]]; then
    local MEMBER_ID="$(echo "${MEMBER_LIST}" | jq -r ".members[] | select(contains({clientURLs: [\"/${IPADDR}:\"]})) | .id")"
    test "${MEMBER_ID}" && curl -s "http://127.0.0.1:${ETCD_CLIENT_PORT}/v2/members/${MEMBER_ID}" -XDELETE
    if [[ "${LOCAL_ETCD}" == "true" ]]; then
      docker stop k8sup-etcd
      docker rm k8sup-etcd
      rm -rf "/var/lib/etcd/"*
    fi
  fi
}

function show_usage(){
  USAGE="Usage: ${0##*/} [options...]
Options:
-r, --remove                             Exit K8S cluster and remove data
    --stop-k8s-only                      Just stop k8s service without stop etcd service
-f, --force                              Force to kill named k8sup containers
    --exit-local-etcd-only               Exit the local etcd member frome cluster
    --exit-remote-etcd=REMOTE_IPADDR     Exit the remote etcd member frome cluster
-h, --help                               This help text
"

  echo "${USAGE}"
}

function get_options(){
  local PROGNAME="${0##*/}"
  local SHORTOPTS="rfh"
  local LONGOPTS="remove,stop-k8s-only,force,exit-local-etcd-only,exit-remote-etcd:,help"
  local PARSED_OPTIONS=""

  PARSED_OPTIONS="$(getopt -o "${SHORTOPTS}" --long "${LONGOPTS}" -n "${PROGNAME}" -- "$@")" || exit 1
  eval set -- "${PARSED_OPTIONS}"

  # extract options and their arguments into variables.
  while true ; do
      case "$1" in
          -r|--remove)
              export EX_EXIT="true"
              shift
              ;;
             --stop-k8s-only)
              export EX_STOP_K8S_ONLY="true"
              shift
              ;;
          -f|--force)
              export EX_FORCE="true"
              shift
              ;;
             --exit-local-etcd-only)
              export EX_LOCAL_ETCD_ONLY="true"
              shift
              ;;
             --exit-remote-etcd)
              export EX_REMOTE_ETCD="true"
              export EX_REMOTE_IPADDR="$2"
              shift 2
              ;;
          -h|--help)
              show_usage
              exit 0
              shift
              ;;
          --)
              shift
              break
              ;;
          *)
              echo "Option error!" 1>&2
              echo $1
              exit 1
              ;;
      esac
  done

  if [[ "${EX_REMOTE_ETCD}" == "true" ]] && [[ -z "${EX_REMOTE_IPADDR}" ]]; then
    echo "Need IP address of remote etcd node, exiting..." 1>&2
    exit 1
  fi
}

function main(){
  get_options "$@"
  local EXIT="${EX_EXIT}"

  source "/root/.bashrc"
  local IPADDR="${EX_IPADDR}"
  local ETCD_CLIENT_PORT="${EX_ETCD_CLIENT_PORT}"
  local K8S_VERSION="${EX_K8S_VERSION}"
  local K8S_PORT="${EX_K8S_PORT}"
  local REGISTRY="${EX_REGISTRY}"
  local LOCAL_ETCD="true"

  local STOP_K8S_ONLY="${EX_STOP_K8S_ONLY}"
  local EXIT_ETCD_ONLY="${EX_EXIT_ETCD_ONLY}"
  local LOCAL_ETCD_ONLY="${EX_LOCAL_ETCD_ONLY}"
  local REMOTE_ETCD="${EX_REMOTE_ETCD}"
  local REMOTE_IPADDR="${EX_REMOTE_IPADDR}"
  local FORCE="${EX_FORCE}"
  if [[ "${STOP_K8S_ONLY}" == "true" ]]; then
    stop_k8s "${IPADDR}" "${ETCD_CLIENT_PORT}" "${K8S_VERSION}" "${K8S_PORT}" "${REGISTRY}"
    exit 0
  fi
  if [[ "${LOCAL_ETCD_ONLY}" == "true" ]]; then
    exit_etcd "${IPADDR}" "${ETCD_CLIENT_PORT}" "${LOCAL_ETCD}"
    exit 0
  fi
  if [[ "${REMOTE_ETCD}" == "true" ]]; then
    LOCAL_ETCD="false"
    exit_etcd "${REMOTE_IPADDR}" "${ETCD_CLIENT_PORT}" "${LOCAL_ETCD}"
    exit 0
  fi
  if [[ "${FORCE}" == "true" ]]; then
    echo "Trying to kill k8s containers..." 1>&2
    docker stop $(docker ps -a | grep -E "k8sup-kubelet" | awk '{print $1}') 1>/dev/null || true
    docker rm -f -v $(docker ps -a | grep -E "${REGISTRY}/hyperkube|${REGISTRY}/pause|${REGISTRY}/kube-addon-manager" | awk '{print $1}') 1>/dev/null || true
    if [[ "${EXIT}" == "true" ]]; then
      exit_etcd "${IPADDR}" "${ETCD_CLIENT_PORT}" "${LOCAL_ETCD}"
    fi
  else
    # Default removing
    echo "Stopping k8s containers..." 1>&2
    stop_k8s "${IPADDR}" "${ETCD_CLIENT_PORT}" "${K8S_VERSION}" "${K8S_PORT}" "${REGISTRY}"
    if [[ "${EXIT}" == "true" ]]; then
      exit_etcd "${IPADDR}" "${ETCD_CLIENT_PORT}" "${LOCAL_ETCD}"
    fi
  fi

  echo "Stopping k8sup-kubelet, k8sup-etcd, k8sup-flanneld, and k8sup..." 1>&2
  docker stop $(docker ps -a | grep -E "k8s-proxy|k8sup-kubelet|k8sup-flannel|k8sup-etcd" | awk '{print $1}') 1>/dev/null || true
  docker rm -v $(docker ps -a | grep -E "k8s-proxy|k8sup-kubelet|k8sup-flannel|k8sup-etcd" | awk '{print $1}') 1>/dev/null || true

  docker rm -f -v $(docker ps -a | grep "k8sup" | awk '{print $1}') 1>/dev/null
}

main "$@"
