apiVersion: v1
kind: ReplicationController
metadata:
  name: ntp-server
  namespace: kube-system
  labels:
    name: ntp-server
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  selector:
    name: ntp-server
  template:
    metadata:
      labels:
        name: ntp-server
    spec:
      containers:
      - name: ntp-server
        image: NTPSERVER_REGISTRY/ntp-server:K8SUP_NTPSERVER_VERSION
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 123
          protocol: UDP
        volumeMounts:
        - mountPath: /etc/chrony
          name: config-volume
        securityContext:
          privileged: true
      volumes:
      - name: config-volume
        configMap:
          name: ntp-config
